name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory to client
        working-directory: ./client
        run: pwd

      - name: Create .env file in client directory
        working-directory: ./client
        run: |
          touch .env
          echo BASE_URL="https://example.com" > .env
      
      - name: Check if .env file is created
        working-directory: ./client
        run: ls -la

      - name: Display .env file contents
        working-directory: ./client
        run: cat .env
