name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory to client
        working-directory: ./client
        run: pwd

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Create .env file in client directory
        working-directory: ./client
        run: |
          touch .env
          echo BASE_URL="https://example.com" > .env

      - name: Build the React app
        working-directory: ./client
        run: npm run build

      - name: Check if build folder is created
        working-directory: ./client
        run: ls -la build

      - name: Display .env file contents
        working-directory: ./client
        run: cat .env
