name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          touch .env
          echo BASE_URL="https://example.com" > .env
      
      - name: Check if .env file is created
        run: ls -la

      - name: Display .env file contents
        run: cat .env
